# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31665b0bd87e0d075ce315e07d851753f2ff8281feabad6174acee92557d23ade7a2ebf47de701e65bfd199c565a486033aecc075979289614b1457de2818c99

test:
  secret_key_base: 57c5c4aed3feb5860d77ede4ced443ced22fcf5600dedcf64f234e9e96c52aeeba6ed12cafbe49047c3b4ba96e5cfdc7da64918a71fe948fe9380d7e40132d83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
